# SwirlDesk FIELD // Kitty v0.4
font_family JetBrainsMono Nerd Font
font_size 11.0

background #0b0d0a
foreground #d9d3c3
background_opacity 0.985

cursor #b3a06d
cursor_text_color #0b0d0a
cursor_shape block

selection_background #403b2a
selection_foreground #f1ead8

# ANSI palette: deliberately earth-toned; no bright desktop blue/purple.
color0  #090a08
color1  #92534a
color2  #84956b
color3  #c49a52
color4  #66705b
color5  #85796f
color6  #728b72
color7  #d9d3c3

color8  #5e6157
color9  #ad665c
color10 #9cab7d
color11 #d2ad66
color12 #879078
color13 #a29283
color14 #8ba382
color15 #f1ead8

url_color #b3a06d
active_border_color #a68a5b
inactive_border_color #34382f
bell_border_color #c49a52

window_padding_width 8
draw_minimal_borders yes
confirm_os_window_close 0

# Keep tabs technical and quiet when they are needed.
tab_bar_min_tabs 2
tab_bar_style separator
tab_separator " // "
active_tab_foreground #0b0d0a
active_tab_background #a68a5b
inactive_tab_foreground #908a7c
inactive_tab_background #11140f
tab_bar_background #0b0d0a
