background {
    monitor =
    color = rgba(14, 16, 24, 1.0)

    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true

#    outer_color = rgba(137, 180, 250, 0.9)
#    inner_color = rgba(30, 30, 46, 0.9)
#    font_color = rgba(245, 245, 245, 1.0)
    outer_color = rgba(d70a53ee)
    inner_color = rgba(211820ee)
    font_color = rgba(f4e8efff)

    fade_on_empty = false
    placeholder_text = Passwort…

    position = 0, -40
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/.config/swirldesk/assets/swirldesk.png
    size = 220
    rounding = -1
    border_size = 0
    reload_time = -1

    position = 0, 220
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(245, 245, 245, 1.0)
    font_size = 72
    font_family = JetBrains Mono

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] sh -c 'echo "Hallo $(cat ~/.config/swirldesk/state/display_name 2>/dev/null || whoami)"'
#    color = rgba(205, 214, 244, 0.9)
    color = rgba(f4e8efee) 
    font_size = 22
    font_family = JetBrains Mono

    position = 0, 55
    halign = center
    valign = center
}
