# source = ~/.config/hypr/themes/catppuccin-mocha.conf
source = ~/.config/swirldesk/state/current_theme/hypr/colors.conf
source = ~/.config/swirldesk/state/current_theme/hypr/appearance.conf
source = ~/.config/swirldesk/state/current_theme/hypr/cursor.conf

source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
# source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
