font_family JetBrainsMono Nerd Font
font_size 11.0

background #1f2228
foreground #dce0e8

cursor #7aa2f7

selection_background #2a2e36
selection_foreground #dce0e8

color0 #17191f
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #8bd5ca
color7 #dce0e8

color8 #5c6370
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #8bd5ca
color15 #ffffff

window_padding_width 8
background_opacity 0.94
confirm_os_window_close 0
