general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2

    col.active_border = $accent $accent2 45deg
    col.inactive_border = $border_inactive

    layout = dwindle
}

decoration {
    rounding = 12

    blur {
        enabled = true
        size = 7
        passes = 3
        vibrancy = 0.14
    }

    shadow {
        enabled = true
        range = 18
        render_power = 3
        color = $shadow_color
    }
}

animations {
    enabled = true

    bezier = graphite_decel, 0.05, 0.7, 0.1, 1.0
    bezier = graphite_accel, 0.3, 0.0, 0.8, 0.15
    bezier = graphite_standard, 0.2, 0.0, 0, 1.0

    animation = windows, 1, 4, graphite_decel, popin 80%
    animation = windowsOut, 1, 3, graphite_accel, popin 80%
    animation = border, 1, 6, graphite_standard
    animation = fade, 1, 4, graphite_decel
    animation = workspaces, 1, 4, graphite_decel, slide
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
}
