exec-once = waybar
exec-once = dunst
exec-once = nm-applet
exec-once = hypridle
exec-once = nextcloud
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/xdg-desktop-portal
exec-once = /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
exec-once = xfsettingsd
# exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = ~/.config/hypr/scripts/wallpaper.sh
exec-once = ~/.config/swirldesk/scripts/wallpaper-restore.sh

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = ~/.config/swirldesk/scripts/monitor-hotplug-watch.sh
exec-once = sleep 3 && ~/.config/swirldesk/scripts/lid-monitor.sh sync
