#monitor = ,preferred,auto,1

# Fallback, falls keine nwg-displays-Datei existiert
monitor = ,preferred,auto,1

# SwirlDesk Monitor-Konfiguration
# Diese Datei lädt die von nwg-displays erzeugte Monitor-Konfiguration.

source = ~/.config/hypr/monitors-nwg.conf
