windowrule {
    name = float-pavucontrol
    match:class = ^(pavucontrol)$
    float = on
}

windowrule {
    name = float-network-editor
    match:class = ^(nm-connection-editor)$
    float = on
}

windowrule {
    name = pip-floating
    match:title = ^(Picture-in-Picture)$
    float = on
    pin = on
}

windowrule = match:class ^(btop-floating)$, float on
windowrule = match:class ^(btop-floating)$, size 950 620
windowrule = match:class ^(btop-floating)$, center on
