font_family JetBrainsMono Nerd Font
font_size 11.0

background #151116
foreground #f4e8ef

cursor #d70a53

selection_background #2c202b
selection_foreground #f4e8ef

color0 #0f0b10
color1 #f7768e
color2 #8bd49c
color3 #f0b86e
color4 #82aaff
color5 #d70a53
color6 #ff4f8b
color7 #f4e8ef

color8 #5b4655
color9 #f7768e
color10 #8bd49c
color11 #f0b86e
color12 #82aaff
color13 #ff4f8b
color14 #ce0058
color15 #ffffff

window_padding_width 8
background_opacity 0.94
confirm_os_window_close 0
