# SwirlDesk Debian Colors

$bg        = rgb(151116)
$bg_dark   = rgb(0f0b10)
$bg_light  = rgb(211820)
$surface   = rgb(2c202b)

$fg        = rgb(f4e8ef)
$fg_muted  = rgb(c8aebb)

$accent    = rgb(d70a53)
$accent2   = rgb(ce0058)
$accent3   = rgb(ff4f8b)

$red       = rgb(f7768e)
$orange    = rgb(f0b86e)
$yellow    = rgb(e8d48a)
$green     = rgb(8bd49c)
$blue      = rgb(82aaff)
$purple    = rgb(c792ea)

$border_inactive = rgba(5b465555)
$shadow_color    = rgba(00000077)
